# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]  # Runs at midnight on Sunday
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: METRICS_TOKEN
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{secrets.METRICS_TOKEN}}
            # The following scopes are required:
                # - public_access (default scope)
            # The following additional scopes may be required:
                # - read:org      (for organization related metrics)
                # - read:user     (for user related data)
                # - read:packages (for some packages related data)
                # - repo          (optional, if you want to include private repositories)
          user: nomadicGopher
          base: ""
          config_octicon: yes
          config_timezone: America/New_York
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_skipped: Sandbox
          plugin_languages_limit: 10
          #plugin_languages_other: yes
          #base_hireable: yes
